import type { JobCategory, InterviewQuestion } from './types';

export const JOB_CATEGORIES: JobCategory[] = [
  {
    id: 'software',
    label: '소프트웨어 개발',
    labelEn: 'Software Development',
    icon: '💻',
    description: '프론트엔드, 백엔드, 풀스택 개발자',
    questionCount: 20,
    color: '#4F46E5',
  },
  {
    id: 'product',
    label: '프로덕트 매니지먼트',
    labelEn: 'Product Management',
    icon: '📊',
    description: 'PM, PO 포지션',
    questionCount: 8,
    color: '#0891B2',
  },
  {
    id: 'design',
    label: 'UX/UI 디자인',
    labelEn: 'UX/UI Design',
    icon: '🎨',
    description: '프로덕트 디자이너, UX 리서처',
    questionCount: 6,
    color: '#7C3AED',
  },
  {
    id: 'data',
    label: '데이터 사이언스',
    labelEn: 'Data Science',
    icon: '📈',
    description: '데이터 분석가, ML 엔지니어',
    questionCount: 8,
    color: '#059669',
  },
  {
    id: 'marketing',
    label: '마케팅',
    labelEn: 'Marketing',
    icon: '📣',
    description: '디지털 마케터, 그로스 해커',
    questionCount: 5,
    color: '#DC2626',
  },
  {
    id: 'hr',
    label: '인사/조직',
    labelEn: 'HR & People',
    icon: '👥',
    description: 'HR, 리크루터, 조직문화',
    questionCount: 5,
    color: '#D97706',
  },
];

export const MOCK_QUESTIONS: Record<string, InterviewQuestion[]> = {
  software: [
    // ── Behavioral ──────────────────────────────────────────────────────────
    {
      id: 'sw-001',
      categoryId: 'software',
      text: '자신의 가장 큰 기술적 성과에 대해 설명해 주세요.',
      hint: 'STAR 방법론(상황-과제-행동-결과)을 활용하면 효과적입니다.',
      difficulty: 'medium',
      tags: ['경험', '성과'],
      estimatedSeconds: 120,
    },
    {
      id: 'sw-002',
      categoryId: 'software',
      text: '팀에서 기술적 의견 충돌이 생겼을 때 어떻게 해결했나요?',
      hint: '구체적인 상황과 본인의 역할을 중심으로 설명하세요.',
      difficulty: 'medium',
      tags: ['협업', '갈등해결'],
      estimatedSeconds: 90,
    },
    {
      id: 'sw-003',
      categoryId: 'software',
      text: '시스템 장애가 발생했을 때 어떻게 대응하셨는지 경험을 말씀해 주세요.',
      hint: '문제 인식 → 원인 파악 → 해결 → 사후 조치 순서로 설명하면 좋습니다.',
      difficulty: 'hard',
      tags: ['온콜', '문제해결', '운영'],
      estimatedSeconds: 150,
    },
    {
      id: 'sw-004',
      categoryId: 'software',
      text: '코드 리뷰에서 본인이 가장 중요하게 생각하는 기준은 무엇인가요?',
      difficulty: 'medium',
      tags: ['코드품질', '협업'],
      estimatedSeconds: 100,
    },
    // ── Computer Science fundamentals ────────────────────────────────────────
    {
      id: 'sw-005',
      categoryId: 'software',
      text: '시간 복잡도 O(n log n)과 O(n²)의 차이를 설명하고, 각각이 적합한 상황을 예시로 들어 주세요.',
      hint: '정렬 알고리즘을 예시로 들면 답변하기 쉽습니다.',
      difficulty: 'medium',
      tags: ['알고리즘', '복잡도', 'CS기초'],
      estimatedSeconds: 120,
    },
    {
      id: 'sw-006',
      categoryId: 'software',
      text: '동시성(Concurrency)과 병렬성(Parallelism)의 차이를 설명하고, 각각 어떤 문제를 해결하는지 말씀해 주세요.',
      difficulty: 'hard',
      tags: ['동시성', '병렬처리', 'CS기초'],
      estimatedSeconds: 130,
    },
    {
      id: 'sw-007',
      categoryId: 'software',
      text: '재귀(Recursion)와 반복문(Iteration)의 차이점은 무엇이고, 재귀 사용 시 스택 오버플로우를 어떻게 방지하나요?',
      hint: '꼬리 재귀 최적화(Tail Call Optimization)를 언급하면 좋습니다.',
      difficulty: 'medium',
      tags: ['알고리즘', 'CS기초'],
      estimatedSeconds: 110,
    },
    // ── System design & architecture ─────────────────────────────────────────
    {
      id: 'sw-008',
      categoryId: 'software',
      text: '마이크로서비스와 모놀리식 아키텍처의 장단점을 비교하고, 어떤 상황에서 각각을 선택하시겠나요?',
      difficulty: 'hard',
      tags: ['아키텍처', '시스템설계'],
      estimatedSeconds: 150,
    },
    {
      id: 'sw-009',
      categoryId: 'software',
      text: '대용량 트래픽을 처리하는 시스템을 설계할 때 고려해야 할 요소들을 설명해 주세요.',
      hint: '로드 밸런싱, 캐싱, 데이터베이스 샤딩, CDN 등을 언급해 보세요.',
      difficulty: 'hard',
      tags: ['시스템설계', '확장성', '성능'],
      estimatedSeconds: 180,
    },
    {
      id: 'sw-010',
      categoryId: 'software',
      text: '캐싱 전략(LRU, write-through, write-back 등)에 대해 설명하고 실제 적용 경험을 말씀해 주세요.',
      difficulty: 'hard',
      tags: ['캐싱', '성능', '시스템설계'],
      estimatedSeconds: 140,
    },
    // ── Databases ────────────────────────────────────────────────────────────
    {
      id: 'sw-011',
      categoryId: 'software',
      text: '데이터베이스 인덱스가 무엇이고, 언제 인덱스를 추가하거나 제거해야 하는지 설명해 주세요.',
      hint: '인덱스의 읽기 성능 향상과 쓰기 성능 저하 트레이드오프를 언급하세요.',
      difficulty: 'medium',
      tags: ['데이터베이스', '성능', '인덱스'],
      estimatedSeconds: 130,
    },
    {
      id: 'sw-012',
      categoryId: 'software',
      text: '트랜잭션의 ACID 속성(원자성, 일관성, 격리성, 지속성)에 대해 각각 설명해 주세요.',
      difficulty: 'medium',
      tags: ['데이터베이스', 'ACID', 'CS기초'],
      estimatedSeconds: 130,
    },
    {
      id: 'sw-013',
      categoryId: 'software',
      text: 'SQL의 INNER JOIN, LEFT JOIN, RIGHT JOIN, FULL OUTER JOIN의 차이를 설명해 주세요.',
      hint: '벤 다이어그램을 머릿속으로 떠올리며 설명하면 명확합니다.',
      difficulty: 'easy',
      tags: ['데이터베이스', 'SQL'],
      estimatedSeconds: 100,
    },
    // ── Web & APIs ───────────────────────────────────────────────────────────
    {
      id: 'sw-014',
      categoryId: 'software',
      text: 'RESTful API와 GraphQL의 장단점을 비교하고, 어떤 상황에 각각을 선택하시겠나요?',
      difficulty: 'medium',
      tags: ['API설계', '백엔드', '아키텍처'],
      estimatedSeconds: 130,
    },
    {
      id: 'sw-015',
      categoryId: 'software',
      text: '웹 애플리케이션에서 XSS와 CSRF 공격이 무엇이고, 각각 어떻게 방어하나요?',
      difficulty: 'medium',
      tags: ['보안', '웹', 'XSS', 'CSRF'],
      estimatedSeconds: 130,
    },
    {
      id: 'sw-016',
      categoryId: 'software',
      text: 'TCP와 UDP의 차이점과 각각의 대표적인 사용 사례를 설명해 주세요.',
      difficulty: 'medium',
      tags: ['네트워크', 'CS기초'],
      estimatedSeconds: 110,
    },
    // ── Frontend ─────────────────────────────────────────────────────────────
    {
      id: 'sw-017',
      categoryId: 'software',
      text: 'React의 가상 DOM(Virtual DOM)이 무엇이고, 실제 DOM과 비교했을 때 어떤 이점이 있나요?',
      difficulty: 'medium',
      tags: ['React', '프론트엔드', '성능'],
      estimatedSeconds: 120,
    },
    // ── Engineering practices ─────────────────────────────────────────────────
    {
      id: 'sw-018',
      categoryId: 'software',
      text: 'Git에서 merge와 rebase의 차이점을 설명하고, 팀 협업 시 어떤 전략을 선호하시나요?',
      difficulty: 'medium',
      tags: ['Git', '협업', '버전관리'],
      estimatedSeconds: 110,
    },
    {
      id: 'sw-019',
      categoryId: 'software',
      text: '객체지향 프로그래밍의 SOLID 원칙에 대해 설명하고, 실제 코드에서 적용해 본 경험을 말씀해 주세요.',
      difficulty: 'hard',
      tags: ['OOP', '설계원칙', '아키텍처'],
      estimatedSeconds: 150,
    },
    {
      id: 'sw-020',
      categoryId: 'software',
      text: '새로운 기술을 도입하기 전에 어떤 기준으로 검토하고 팀을 어떻게 설득하시나요?',
      difficulty: 'medium',
      tags: ['기술선택', '의사결정', '리더십'],
      estimatedSeconds: 120,
    },
  ],

  product: [
    {
      id: 'pm-001',
      categoryId: 'product',
      text: '프로덕트 로드맵을 결정할 때 어떤 기준으로 우선순위를 정하시나요?',
      hint: 'RICE, ICE 등 프레임워크를 언급하면 구체적으로 보입니다.',
      difficulty: 'medium',
      tags: ['우선순위', '전략', '의사결정'],
      estimatedSeconds: 120,
    },
    {
      id: 'pm-002',
      categoryId: 'product',
      text: '데이터 없이 제품 결정을 내려야 했던 경험이 있으신가요?',
      difficulty: 'hard',
      tags: ['의사결정', '불확실성'],
      estimatedSeconds: 120,
    },
    {
      id: 'pm-003',
      categoryId: 'product',
      text: 'A/B 테스트를 설계할 때 중요하게 고려해야 할 통계적 요소는 무엇인가요?',
      hint: '표본 크기, 통계적 유의성, 검정력(Power)을 언급해 보세요.',
      difficulty: 'hard',
      tags: ['A/B테스트', '데이터', '통계'],
      estimatedSeconds: 130,
    },
    {
      id: 'pm-004',
      categoryId: 'product',
      text: '사용자 리텐션이 낮을 때 원인을 어떻게 진단하고 어떤 액션을 취하시겠나요?',
      difficulty: 'hard',
      tags: ['리텐션', '분석', '성장'],
      estimatedSeconds: 140,
    },
    {
      id: 'pm-005',
      categoryId: 'product',
      text: '개발팀과 비즈니스팀 사이에서 요구사항이 충돌할 때 어떻게 중재하시나요?',
      difficulty: 'medium',
      tags: ['커뮤니케이션', '협업', '이해관계자'],
      estimatedSeconds: 110,
    },
    {
      id: 'pm-006',
      categoryId: 'product',
      text: '출시 후 핵심 지표(DAU, 전환율 등)가 목표 대비 낮을 때 어떻게 접근하시겠나요?',
      difficulty: 'hard',
      tags: ['지표', '분석', '의사결정'],
      estimatedSeconds: 140,
    },
    {
      id: 'pm-007',
      categoryId: 'product',
      text: '기술 부채(Technical Debt)를 PM 관점에서 어떻게 바라보고 로드맵에 어떻게 반영하시나요?',
      difficulty: 'hard',
      tags: ['기술부채', '로드맵', '개발협업'],
      estimatedSeconds: 130,
    },
    {
      id: 'pm-008',
      categoryId: 'product',
      text: '경쟁사 제품과 차별화 포인트를 찾기 위해 어떤 분석 방법을 사용하시나요?',
      difficulty: 'medium',
      tags: ['경쟁분석', '전략', '리서치'],
      estimatedSeconds: 110,
    },
  ],

  design: [
    {
      id: 'ux-001',
      categoryId: 'design',
      text: '사용자 리서치 결과가 이해관계자의 기대와 다를 때 어떻게 설득하시나요?',
      difficulty: 'hard',
      tags: ['리서치', '커뮤니케이션', '설득'],
      estimatedSeconds: 120,
    },
    {
      id: 'ux-002',
      categoryId: 'design',
      text: '접근성(Accessibility)을 고려한 디자인이 왜 중요하고, 실제로 어떻게 반영하시나요?',
      hint: 'WCAG 기준, 색상 대비, 스크린 리더 지원 등을 언급해 보세요.',
      difficulty: 'medium',
      tags: ['접근성', 'a11y', '포용디자인'],
      estimatedSeconds: 110,
    },
    {
      id: 'ux-003',
      categoryId: 'design',
      text: '디자인 시스템을 구축하거나 운영한 경험이 있으신가요? 어떤 점이 가장 어려웠나요?',
      difficulty: 'hard',
      tags: ['디자인시스템', '협업', '확장성'],
      estimatedSeconds: 130,
    },
    {
      id: 'ux-004',
      categoryId: 'design',
      text: '사용성 테스트에서 예상치 못한 결과가 나왔을 때 어떻게 대응하셨나요?',
      difficulty: 'medium',
      tags: ['사용성테스트', '리서치', '반복설계'],
      estimatedSeconds: 110,
    },
    {
      id: 'ux-005',
      categoryId: 'design',
      text: '모바일 퍼스트 디자인과 데스크탑 퍼스트 디자인의 차이점과 각각의 적합한 상황을 설명해 주세요.',
      difficulty: 'medium',
      tags: ['반응형', '모바일', 'UX'],
      estimatedSeconds: 100,
    },
    {
      id: 'ux-006',
      categoryId: 'design',
      text: '개발자와 협업할 때 디자인 의도가 잘못 구현되는 상황을 어떻게 줄이시나요?',
      difficulty: 'medium',
      tags: ['개발협업', '핸드오프', '커뮤니케이션'],
      estimatedSeconds: 110,
    },
  ],

  data: [
    {
      id: 'ds-001',
      categoryId: 'data',
      text: '과적합(Overfitting)이란 무엇이고, 어떻게 방지하나요?',
      hint: '정규화, 드롭아웃, 교차검증, 데이터 증강 등을 언급해 보세요.',
      difficulty: 'medium',
      tags: ['머신러닝', '과적합', '모델링'],
      estimatedSeconds: 120,
    },
    {
      id: 'ds-002',
      categoryId: 'data',
      text: '분류 모델의 평가 지표인 정확도, 정밀도, 재현율, F1 스코어의 차이를 설명해 주세요.',
      hint: '불균형 데이터셋에서 정확도만으로 평가하면 왜 위험한지 언급하면 좋습니다.',
      difficulty: 'medium',
      tags: ['분류', '평가지표', '머신러닝'],
      estimatedSeconds: 130,
    },
    {
      id: 'ds-003',
      categoryId: 'data',
      text: '지도학습과 비지도학습의 차이점을 실제 비즈니스 예시와 함께 설명해 주세요.',
      difficulty: 'easy',
      tags: ['머신러닝', '지도학습', '비지도학습'],
      estimatedSeconds: 110,
    },
    {
      id: 'ds-004',
      categoryId: 'data',
      text: '결측값(Missing Value)을 처리하는 다양한 방법과 각각의 장단점을 설명해 주세요.',
      hint: '삭제, 평균/중앙값 대체, KNN 대체, 모델 기반 대체 등을 비교해 보세요.',
      difficulty: 'medium',
      tags: ['데이터전처리', '결측값', '피처엔지니어링'],
      estimatedSeconds: 120,
    },
    {
      id: 'ds-005',
      categoryId: 'data',
      text: '모델의 정확도보다 중요한 비즈니스 지표가 있다고 생각하시나요? 예시를 들어 설명해 주세요.',
      difficulty: 'hard',
      tags: ['비즈니스', '모델링', '지표'],
      estimatedSeconds: 130,
    },
    {
      id: 'ds-006',
      categoryId: 'data',
      text: 'SQL과 Python(pandas) 중 데이터 분석에 어느 쪽을 선호하시나요? 각각 어떤 상황에서 사용하시나요?',
      difficulty: 'easy',
      tags: ['SQL', 'Python', '데이터분석'],
      estimatedSeconds: 100,
    },
    {
      id: 'ds-007',
      categoryId: 'data',
      text: '인과관계(Causation)와 상관관계(Correlation)의 차이를 예시를 들어 설명하고, 데이터 분석에서 왜 중요한지 말씀해 주세요.',
      difficulty: 'medium',
      tags: ['통계', '인과관계', '분석'],
      estimatedSeconds: 130,
    },
    {
      id: 'ds-008',
      categoryId: 'data',
      text: '대용량 데이터셋(수억 건 이상)을 처리할 때 어떤 기술과 전략을 사용하시나요?',
      hint: '분산처리(Spark), 파티셔닝, 청크 처리, 열 지향 스토리지(Parquet) 등을 언급해 보세요.',
      difficulty: 'hard',
      tags: ['빅데이터', '분산처리', '성능'],
      estimatedSeconds: 140,
    },
  ],

  marketing: [
    {
      id: 'mkt-001',
      categoryId: 'marketing',
      text: '마케팅 캠페인의 성과를 측정할 때 어떤 지표를 가장 중요하게 보시나요? 그 이유는 무엇인가요?',
      difficulty: 'medium',
      tags: ['지표', 'KPI', '성과측정'],
      estimatedSeconds: 110,
    },
    {
      id: 'mkt-002',
      categoryId: 'marketing',
      text: '제한된 예산으로 최대 효과를 낼 수 있는 디지털 마케팅 채널을 어떻게 선택하시나요?',
      hint: '타겟 오디언스, CAC, ROAS 등의 개념을 언급하면 좋습니다.',
      difficulty: 'hard',
      tags: ['예산최적화', '채널전략', '그로스'],
      estimatedSeconds: 130,
    },
    {
      id: 'mkt-003',
      categoryId: 'marketing',
      text: '퍼포먼스 마케팅과 브랜드 마케팅의 차이점을 설명하고, 두 가지를 어떻게 균형 있게 운영하시나요?',
      difficulty: 'medium',
      tags: ['브랜드', '퍼포먼스', '전략'],
      estimatedSeconds: 120,
    },
    {
      id: 'mkt-004',
      categoryId: 'marketing',
      text: '고객 획득 비용(CAC)이 증가하고 있을 때 어떤 방식으로 원인을 분석하고 개선하시겠나요?',
      difficulty: 'hard',
      tags: ['CAC', '그로스', '분석'],
      estimatedSeconds: 130,
    },
    {
      id: 'mkt-005',
      categoryId: 'marketing',
      text: '콘텐츠 마케팅 전략을 수립할 때 타겟 오디언스를 어떻게 정의하고 메시지를 설계하시나요?',
      difficulty: 'medium',
      tags: ['콘텐츠', '타겟팅', '전략'],
      estimatedSeconds: 120,
    },
  ],

  hr: [
    {
      id: 'hr-001',
      categoryId: 'hr',
      text: '채용 과정에서 후보자의 문화적 적합성(Cultural Fit)을 어떻게 평가하시나요?',
      difficulty: 'medium',
      tags: ['채용', '문화', '평가'],
      estimatedSeconds: 110,
    },
    {
      id: 'hr-002',
      categoryId: 'hr',
      text: '직원 이직률이 높을 때 원인을 어떻게 진단하고 어떤 방식으로 개선하시겠나요?',
      difficulty: 'hard',
      tags: ['리텐션', '조직문화', '분석'],
      estimatedSeconds: 130,
    },
    {
      id: 'hr-003',
      categoryId: 'hr',
      text: '성과 관리 시스템을 설계할 때 가장 중요하게 고려하는 요소는 무엇인가요?',
      hint: 'OKR, KPI, 360도 피드백 등의 프레임워크를 언급해 보세요.',
      difficulty: 'medium',
      tags: ['성과관리', 'OKR', '조직설계'],
      estimatedSeconds: 120,
    },
    {
      id: 'hr-004',
      categoryId: 'hr',
      text: '다양성과 포용성(D&I)을 채용 및 조직 문화에서 실질적으로 구현하기 위해 어떤 활동을 하셨나요?',
      difficulty: 'hard',
      tags: ['다양성', '포용성', '조직문화'],
      estimatedSeconds: 130,
    },
    {
      id: 'hr-005',
      categoryId: 'hr',
      text: '직원이 번아웃 징후를 보일 때 리더나 HR 담당자로서 어떻게 접근하시나요?',
      difficulty: 'medium',
      tags: ['번아웃', '웰빙', '리더십'],
      estimatedSeconds: 110,
    },
  ],
};

export const DIFFICULTY_LABELS: Record<InterviewQuestion['difficulty'], string> = {
  easy: '초급',
  medium: '중급',
  hard: '고급',
};
